name: Build and Deploy Java Project to EC2

on:
  workflow_dispatch:
    inputs:
      TestOrProd:
        description: 'Is this a test deploy or a production deploy'
        required: true
        default: 'TEST'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x backend/gradlew
    - name: Prep applications.properties with username/password
      env:
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_ADDRESS: 127.0.0.1
      run: |
        cd backend
        chmod +x update_applications.properties.sh
        ./update_applications.properties.sh
    - name: Build with Gradle
      run: cd backend; ./gradlew build
    - name: Clean ec2 instance deployment
      uses: appleboy/ssh-action@master
      with:
        host: 52.14.239.79
        username: ec2-user
        key : ${{ secrets.EC2_KEY }}
        port: 22
        script: killall -q java; rm -r ~/cs471project/backend/*
    - name: Move files to proper location to scp
      run: mv backend/build/libs/studentLoanSystem*.jar .; mv backend/startscript.sh .
    - name: Copy files to ec2 instance
      uses: appleboy/scp-action@master
      with:
        host: 52.14.239.79
        username: ec2-user
        key : ${{ secrets.EC2_KEY }}
        port: 22
        source: "studentLoanSystem*.jar,startscript.sh"
        target: "~/cs471project/backend/"
    - name: Start backend deployment
      uses: appleboy/ssh-action@master
      with:
        host: 52.14.239.79
        username: ec2-user
        key : ${{ secrets.EC2_KEY }}
        port: 22
        script: "cd ~/cs471project/backend/; chmod +x startscript.sh; ./startscript.sh ${{ github.events.inputs.TestOrProd }}"
        
