name: Deploy Frontend
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Move Files
      run: mv frontend/html .; mv frontend/config .; mv frontend/sources .
    - name: Create env-config.ini
      run: touch config/env-config.ini; echo "env=prod">config/env-config.ini
    - name: Clean ec2 instance deployment
      uses: appleboy/ssh-action@master
      with:
        host: 52.14.239.79
        username: ec2-user
        key : ${{ secrets.EC2_KEY }}
        port: 22
        script: rm -r /var/www/html/*; rm -r /var/www/sources/*; rm -r /var/www/config/*
    - name: Copy files to ec2 instance
      uses: appleboy/scp-action@master
      with:
        host: 52.14.239.79
        username: ec2-user
        key : ${{ secrets.EC2_KEY }}
        port: 22
        source: "html,sources,config"
        target: "/var/www/"